<?php
namespace Rails\ActiveRecord\Adapter\Schema;

use Zend\Db\Adapter\Driver\ConnectionInterface;

/**
 * These "importers" are expected to be used only with files
 * that were generated by Rails, or with data exported by the
 * framework's exporters. They simply execute queries that are
 * written in certain way.
 */
abstract class AbstractImporter
{
    protected $connection;
    
    /**
     * @param string $sql
     */
    abstract public function import($sql);
    
    public function __construct(ConnectionInterface $connection)
    {
        $this->connection = $connection;
    }
    
    /**
     * @param string $file Full path to file
     */
    public function importFile($file)
    {
        return $this->import(file_get_contents($file));
    }
}
